NET=clr
OS=windows
IPY_DIR="C:\Program Files\IronPython 2.6"

ifeq ($(NET),clr)
  CSC=csc
else ifeq ($(NET),mono)
  #CSC=gmcs
  # Temporary workaround until assembly loading is figured out
  CSC=gmcs /nostdlib /r:mscorlib.dll
endif

ifeq ($(OS),windows)
  PYTHON_DLL=C:/WINDOWS/system32/python26.dll
  OBJ_FORMAT=win32
  RM=del
else ifeq ($(OS),linux)
  PYTHON_DLL=/usr/lib/libpython2.6.so.1
  OBJ_FORMAT=elf32
  RM=rm -f
endif

# CYGWIN hacksip
ifdef IRONCLAD_USE_CYGWIN
   RM=rm -f
   CFLAGS += -mno-cygwin
endif

# Try earnestly to do the right thing.
ifeq ($(TERM),cygwin)
  CFLAGS += -mno-cygwin
endif


