= Overview =

Ironclad's purpose is to allow IronPython to transparently import and use
compiled CPython extensions.

The original project https://code.google.com/p/ironclad is no longer
active. The last known version works with Python 2.6. The idea here is
to make it work with current version (2.7.x) of CPython and IronPython.

At the moment it does compile using up to date components and passes
almost all internal tests.

```
Ran 479 tests in 135.893s
FAILED (failures=2)
scons: done building targets.
```

numpy is still failing on import.

== Building ==

=== Building using Docker ===
This repo contains a Dockerfile that sets up a dockerized build environment
(requires Windows). Using PowerShell:
```
docker build -t ironclad-build:latest -m 2GB .
docker run -it -v ${pwd}:C:\ironclad ironclad-build
```
In the container shell:
```
cd C:\ironclad
scons
```

=== Previous build instructions ===

Previous building instructions can be found at:
https://github.com/IronLanguages/ironclad/wiki/building

== Releases ==

Hold on.


== Hacking ==

Anybody who would like to help is welcome!

See doc/details.txt

