= Overview =

Ironclad's purpose is to allow IronPython to transparently import and use
compiled CPython extensions.

The original project https://code.google.com/p/ironclad is no longer
active. The last known version works with Python 2.6. The idea here is
to make it work with current version of IronPython (3.4.x)
and the corresponding version of CPython (3.4.4).

At the moment it does compile using up to date components and passes
most of internal tests. Most of the remaining work is tracked under Issues.

```
Ran 428 tests in 46.569s

FAILED (failures=1, errors=8, skipped=2)
scons: done building targets.
```

numpy is still failing on import.

== Building ==

=== Building using Docker ===

This repo contains a Dockerfile that sets up a dockerized build environment
(requires Windows; Docker has to be set to use Windows containers).

Using PowerShell:
```
docker build -t ironclad-build:v3.4 -m 2GB .
docker run -it -v ${pwd}:C:\ironclad ironclad-build:v3.4
```
In the container shell:
```
cd C:\ironclad
scons
```
To run all tests:
```
scons test
```

=== Previous build instructions ===

Previous building instructions can be found at:
https://github.com/IronLanguages/ironclad/wiki/building

== Releases ==

Hold on.


== Hacking ==

Anybody who would like to help is welcome!

See doc/details.txt

