../Python25Mapper_exceptions.cs : exceptions builtin_exceptions store_dispatch numbers_operator numbers_convert_c2py numbers_convert_py2c fill_types ../../tools/generatepython25mapper.py
	ipy ../../tools/generatepython25mapper.py
