import sys
args = sys.argv[1:]

def read(filename):
    stream = file(filename)
    try:
	return stream.read()
    finally:
	stream.close()

if len(args) != 2:
    print >>sys.stderr, "usage: tools/insertfiles template inserted-file"

template_file, inserted_file = args
template = read(template_file)
output = template % read(inserted_file).replace('"', r'\"')
sys.stdout.write("/* generated by tools/insertfiles %s %s */\n" % (template_file, inserted_file))
sys.stdout.write(output)


