/* generated by tools/insertfiles CodeSnippets_kindaDictProxy.cs.src kindadictproxy.py */
namespace Ironclad
{
    internal partial class CodeSnippets
    {
        // kindadictproxy.py is inserted here
        public const string KINDA_DICT_PROXY_CODE = @"
from UserDict import UserDict

class KindaDictProxy(UserDict):
    
    def __setitem__(self, key, value):
        raise TypeError('read-only dict')
    
    def __delitem__(self, key):
        raise TypeError('read-only dict')
        
";
    }
}
